// client/src/components/navigation.tsx
import { useState } from "react";
import { Link, useLocation } from "wouter";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Palette, Menu, X } from "lucide-react";

export default function Navigation() {
  const [location] = useLocation();
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

  const navItems = [
    { href: "/", label: "Home" },
    { href: "/portfolio", label: "Portfolio" },
    { href: "#case-studies", label: "Case Studies" },
    { href: "#about", label: "About" },
  ];

  return (
    <motion.nav 
      initial={{ opacity: 0, y: -20 }}
      animate={{ opacity: 1, y: 0 }}
      className="fixed top-0 left-0 right-0 z-50 bg-white/80 backdrop-blur-md border-b border-gray-100"
    >
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16">
          <Link href="/">
            <div className="flex items-center space-x-2 cursor-pointer">
              <div className="w-8 h-8 bg-accent rounded-lg flex items-center justify-center">
                <Palette className="text-white h-4 w-4" />
              </div>
              <span className="text-xl font-bold text-portfolio-primary">Portfolio Hub</span>
            </div>
          </Link>
          
          <div className="hidden md:flex items-center space-x-8">
            {navItems.map((item) => (
              <Link 
                key={item.href} 
                href={item.href}
                className={`text-gray-600 hover:text-accent transition-colors duration-200 ${
                  location === item.href ? 'text-accent font-medium' : ''
                }`}
              >
                {item.label}
              </Link>
            ))}
            <Button className="bg-accent text-white hover:bg-accent/90 rounded-full px-6">
              Contact Us
            </Button>
          </div>
          
          <button 
            className="md:hidden p-2"
            onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
          >
            {isMobileMenuOpen ? <X className="h-6 w-6" /> : <Menu className="h-6 w-6" />}
          </button>
        </div>

        {/* Mobile menu */}
        {isMobileMenuOpen && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }}
            className="md:hidden bg-white border-t border-gray-100"
          >
            <div className="px-2 pt-2 pb-3 space-y-1">
              {navItems.map((item) => (
                <Link
                  key={item.href}
                  href={item.href}
                  className="block px-3 py-2 text-gray-600 hover:text-accent transition-colors duration-200"
                  onClick={() => setIsMobileMenuOpen(false)}
                >
                  {item.label}
                </Link>
              ))}
              <div className="px-3 py-2">
                <Button className="w-full bg-accent text-white hover:bg-accent/90 rounded-full">
                  Contact Us
                </Button>
              </div>
            </div>
          </motion.div>
        )}
      </div>
    </motion.nav>
  );
}

// client/src/components/navigation.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { trigger, transition, style, animate } from '@angular/animations';

@Component({
  selector: 'app-navigation',
  standalone: true,
  imports: [CommonModule],
  template: `
    <nav class="fixed top-0 left-0 right-0 z-50 bg-white/90 backdrop-blur-md border-b border-gray-100" [@slideDown]>
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex items-center justify-between h-16">
          <div class="flex items-center space-x-3">
            <div class="w-10 h-10 bg-gradient-to-r from-blue-500 to-purple-600 rounded-lg flex items-center justify-center">
              <span class="text-white font-bold text-lg">J</span>
            </div>
            <div>
              <span class="text-xl font-bold text-gray-900">Jothika R</span>
              <p class="text-sm text-gray-600">Software Engineer</p>
            </div>
          </div>
          
          <div class="hidden md:flex items-center space-x-8">
            <a *ngFor="let item of navItems" 
               [href]="item.href" 
               class="text-gray-600 hover:text-blue-600 transition-colors duration-200 font-medium"
               (click)="scrollToSection($event, item.href)">
              {{item.label}}
            </a>
            <button class="bg-gradient-to-r from-blue-500 to-purple-600 text-white px-6 py-2 rounded-full hover:shadow-lg transition-all duration-300">
              Contact Me
            </button>
          </div>
          
          <button class="md:hidden p-2" (click)="toggleMobileMenu()">
            <div class="w-6 h-6 flex flex-col justify-center items-center">
              <span class="w-5 h-0.5 bg-gray-600 transform transition-all duration-300" 
                    [class.rotate-45]="isMobileMenuOpen" 
                    [class.translate-y-1.5]="isMobileMenuOpen"></span>
              <span class="w-5 h-0.5 bg-gray-600 my-1 transition-all duration-300" 
                    [class.opacity-0]="isMobileMenuOpen"></span>
              <span class="w-5 h-0.5 bg-gray-600 transform transition-all duration-300" 
                    [class.-rotate-45]="isMobileMenuOpen" 
                    [class.-translate-y-1.5]="isMobileMenuOpen"></span>
            </div>
          </button>
        </div>

        <!-- Mobile menu -->
        <div *ngIf="isMobileMenuOpen" 
             class="md:hidden bg-white border-t border-gray-100 py-4" 
             [@mobileMenu]>
          <div class="space-y-3">
            <a *ngFor="let item of navItems" 
               [href]="item.href" 
               class="block px-3 py-2 text-gray-600 hover:text-blue-600 transition-colors duration-200"
               (click)="scrollToSection($event, item.href); closeMobileMenu()">
              {{item.label}}
            </a>
            <button class="w-full bg-gradient-to-r from-blue-500 to-purple-600 text-white px-6 py-2 rounded-full mt-4">
              Contact Me
            </button>
          </div>
        </div>
      </div>
    </nav>
  `,
  styles: [`
    nav {
      transition: all 0.3s ease;
    }
  `],
  animations: [
    trigger('slideDown', [
      transition(':enter', [
        style({ transform: 'translateY(-100%)', opacity: 0 }),
        animate('500ms ease-out', style({ transform: 'translateY(0)', opacity: 1 }))
      ])
    ]),
    trigger('mobileMenu', [
      transition(':enter', [
        style({ height: 0, opacity: 0 }),
        animate('300ms ease-out', style({ height: '*', opacity: 1 }))
      ]),
      transition(':leave', [
        animate('300ms ease-in', style({ height: 0, opacity: 0 }))
      ])
    ])
  ]
})
export class NavigationComponent {
  isMobileMenuOpen = false;
  
  navItems = [
    { href: '#about', label: 'About' },
    { href: '#skills', label: 'Skills' },
    { href: '#experience', label: 'Experience' },
    { href: '#projects', label: 'Projects' },
    { href: '#education', label: 'Education' },
    { href: '#contact', label: 'Contact' }
  ];

  toggleMobileMenu() {
    this.isMobileMenuOpen = !this.isMobileMenuOpen;
  }

  closeMobileMenu() {
    this.isMobileMenuOpen = false;
  }

  scrollToSection(event: Event, href: string) {
    event.preventDefault();
    const element = document.querySelector(href);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }
}
